### ISSUE TITLE
crash on atm9 startup

### ISSUE THREAD

**Issue by 893203** [SiverDX/pufferfish_unofficial_additions#3]
tried to launch the atm9-0.3.2 pack, crashes saying iron's spells n spellbooks is the cause. posted that bug to their github, and they said it was this mod causing the issue. trying to join a server that some friends have already started playing, and they can all join just fine.

versions:
minecraft 1.20.1
atm9-0.3.2
forge47.3.7
irons_spellbooks- 1.20.1-3.4.0
pufferfish_unofficial_additions- 1.20.1-1.20.0-all

here is a gist link of my crashlog
https://gist.github.com/893203/412917c06ceadb42014ebe3edf3bad3b

**Comment by SiverDX** [comment]
you're using a very old version, i don't know if the other players also do
update to the latest version (incl. other players and server)

**Comment by 893203** [comment]
its not my server, as well, i have tried the latest update of this mod along with some other versions immediately succeeding the above version (1.20.1-1.20.0-all)

here is the crash log for the latest mod version (1.20.1-2.2.2-all)
i have changed nothing else except the version of this mod
https://gist.github.com/893203/fd8f207f07bc5b91c33e37ffba35c0de

**Comment by SiverDX** [comment]
> [14:59:17] [main/INFO]: Found mod file pufferfish_unofficial_additions-1.20.1-1.3.0-all.jar of type MOD with provider {mods folder locator at C:\Users\Pc\curseforge\minecraft\Instances\All the Mods 9 - ATM9\mods}

you still have an old version installed
the newest version can literally not fail because it doesn't use any mixins for iron's spells 'n spellbooks

**Comment by 893203** [comment]
tried updating my java version, and manually validating the mdo version several times to no avail. turns out i custom added this mod to the pack awhile ago, probably around january according to the installed version. still no idea what caused this error
