### ISSUE TITLE
1.21/1.21.1 CTD

### ISSUE THREAD

**Issue by Archannad** [SiverDX/pufferfish_unofficial_additions#4]
As the above states - the current version for 1.21/1.21.1 causes a CTD when loading. When comparing to the previous entries available on Curseforge, it looks as if a wrong or incomplete file has been uploaded in its place?

**Comment by SiverDX** [comment]
Please post a log as I'm not capable of re-producing this crash

The reduced file size is due to not having to bundle https://github.com/LlamaLad7/MixinExtras myself as it is a part of `NeoForge` in 1.21+

**Comment by Archannad** [comment]
Thanks for the quick reply, I've attached logs below. Apologies for not adding them on my initial post! The crash happens both when loading a pre-existing world as well as when creating a new world. As soon as this mod is disabled, I can both load and create worlds without issue.

The specific log attached is when creating a world.

[latest.log](https://github.com/user-attachments/files/18053988/latest.log)

**Comment by SiverDX** [comment]
Should be fixed in the latest version

**Comment by Archannad** [comment]
Just compiled and yeah, all looking good :) Many thanks once again for the quick fix.
